global:
  scrape_interval:     15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'cooking-site'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['laravel.test:80']